### ISSUE TITLE
int vs. long in types_ints.h and cstdint

### ISSUE THREAD

**Issue by BrianPeek** [trapexit/3do-devkit#29]
Hello!  I'm probably missing something, but was curious why the "32" types in `types_ints.h` are declared as `long`, but the "32" types in `cstdint` are declared as `int`?  I realize they're both 4 bytes, but they can't be used interchangeably without casting due to the difference.  Quick example:

```
uint32_t colorEntries[32];

SetScreenColors(sc.sc_Screens[i], colorEntries, 32);
```

The `uint32_t` on `colorEntries` causes a casting error calling `SetScreenColors` because it's expecting a `uint32*`, and these are defined differently.

Thanks!

**Comment by trapexit** [comment]
It's been a while since I worked on ttl (cstdint) and that was at a different time to when I wrote types_ints.h. I really hadn't thought or realized they were different. Probably https://github.com/trapexit/3do-devkit/blob/master/include/3dosdk/2p5/types.h#L46 is why i made u32 long. I don't have any concern changing either to match.

**Comment by trapexit** [comment]
I merged your change though in your original example you should probably be using the proper type rather than expecting uint32_t to be the same.

`graphics.h:Err SetScreenColors(Item screenItem, uint32 *entries, int32 count);
`
